language: java
script:
   - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then mvn package; fi'
   - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then mvn package docker:build docker:push; fi'
sudo: required
services:
  - docker
before_install:
  - docker --version
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
